# Site settings
title: Pave, drawn art
email: pave@pave.rocks
description: > # this means to ignore newlines until "baseurl:"
  I draw portraits mainly by pencils, colored pencils. Most of faces are interesting people like musicians, singers, actors. You can also findanimals or drawn T-shirts. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pave.rocks" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
